name: CI
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 18.x
      - name: Install dependencies
        run: corepack enable && yarn
      - name: Generate GraphQL types
        run: yarn prebuild
      - name: Type Check
        run: yarn tsc
      - name: Run ESLint
        run: yarn eslint
